# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from synapse.v1 import cluster_pb2 as synapse_dot_v1_dot_cluster__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in synapse/v1/cluster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClusterServiceStub:
    """=== Cluster Service ===

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Join = channel.unary_unary(
                '/synapse.v1.ClusterService/Join',
                request_serializer=synapse_dot_v1_dot_cluster__pb2.JoinRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_cluster__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.Leave = channel.unary_unary(
                '/synapse.v1.ClusterService/Leave',
                request_serializer=synapse_dot_v1_dot_cluster__pb2.LeaveRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_cluster__pb2.LeaveResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/synapse.v1.ClusterService/Status',
                request_serializer=synapse_dot_v1_dot_cluster__pb2.StatusRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_cluster__pb2.ClusterStatus.FromString,
                _registered_method=True)
        self.Sync = channel.unary_stream(
                '/synapse.v1.ClusterService/Sync',
                request_serializer=synapse_dot_v1_dot_cluster__pb2.SyncRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_cluster__pb2.SyncEvent.FromString,
                _registered_method=True)


class ClusterServiceServicer:
    """=== Cluster Service ===

    """

    def Join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Leave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=synapse_dot_v1_dot_cluster__pb2.JoinRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_cluster__pb2.JoinResponse.SerializeToString,
            ),
            'Leave': grpc.unary_unary_rpc_method_handler(
                    servicer.Leave,
                    request_deserializer=synapse_dot_v1_dot_cluster__pb2.LeaveRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_cluster__pb2.LeaveResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=synapse_dot_v1_dot_cluster__pb2.StatusRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_cluster__pb2.ClusterStatus.SerializeToString,
            ),
            'Sync': grpc.unary_stream_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=synapse_dot_v1_dot_cluster__pb2.SyncRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_cluster__pb2.SyncEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synapse.v1.ClusterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('synapse.v1.ClusterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClusterService:
    """=== Cluster Service ===

    """

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.ClusterService/Join',
            synapse_dot_v1_dot_cluster__pb2.JoinRequest.SerializeToString,
            synapse_dot_v1_dot_cluster__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Leave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.ClusterService/Leave',
            synapse_dot_v1_dot_cluster__pb2.LeaveRequest.SerializeToString,
            synapse_dot_v1_dot_cluster__pb2.LeaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.ClusterService/Status',
            synapse_dot_v1_dot_cluster__pb2.StatusRequest.SerializeToString,
            synapse_dot_v1_dot_cluster__pb2.ClusterStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/synapse.v1.ClusterService/Sync',
            synapse_dot_v1_dot_cluster__pb2.SyncRequest.SerializeToString,
            synapse_dot_v1_dot_cluster__pb2.SyncEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
