# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from synapse.v1 import conflict_pb2 as synapse_dot_v1_dot_conflict__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in synapse/v1/conflict_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConflictServiceStub:
    """=== Conflict Service ===

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListConflicts = channel.unary_unary(
                '/synapse.v1.ConflictService/ListConflicts',
                request_serializer=synapse_dot_v1_dot_conflict__pb2.ListConflictsRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_conflict__pb2.ListConflictsResponse.FromString,
                _registered_method=True)
        self.ResolveConflict = channel.unary_unary(
                '/synapse.v1.ConflictService/ResolveConflict',
                request_serializer=synapse_dot_v1_dot_conflict__pb2.ResolveConflictRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_conflict__pb2.ResolveConflictResponse.FromString,
                _registered_method=True)
        self.SetPolicy = channel.unary_unary(
                '/synapse.v1.ConflictService/SetPolicy',
                request_serializer=synapse_dot_v1_dot_conflict__pb2.SetPolicyRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_conflict__pb2.SetPolicyResponse.FromString,
                _registered_method=True)


class ConflictServiceServicer:
    """=== Conflict Service ===

    """

    def ListConflicts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveConflict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConflictServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListConflicts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConflicts,
                    request_deserializer=synapse_dot_v1_dot_conflict__pb2.ListConflictsRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_conflict__pb2.ListConflictsResponse.SerializeToString,
            ),
            'ResolveConflict': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveConflict,
                    request_deserializer=synapse_dot_v1_dot_conflict__pb2.ResolveConflictRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_conflict__pb2.ResolveConflictResponse.SerializeToString,
            ),
            'SetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPolicy,
                    request_deserializer=synapse_dot_v1_dot_conflict__pb2.SetPolicyRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_conflict__pb2.SetPolicyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synapse.v1.ConflictService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('synapse.v1.ConflictService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConflictService:
    """=== Conflict Service ===

    """

    @staticmethod
    def ListConflicts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.ConflictService/ListConflicts',
            synapse_dot_v1_dot_conflict__pb2.ListConflictsRequest.SerializeToString,
            synapse_dot_v1_dot_conflict__pb2.ListConflictsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveConflict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.ConflictService/ResolveConflict',
            synapse_dot_v1_dot_conflict__pb2.ResolveConflictRequest.SerializeToString,
            synapse_dot_v1_dot_conflict__pb2.ResolveConflictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.ConflictService/SetPolicy',
            synapse_dot_v1_dot_conflict__pb2.SetPolicyRequest.SerializeToString,
            synapse_dot_v1_dot_conflict__pb2.SetPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
