# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from synapse.v1 import memory_pb2 as synapse_dot_v1_dot_memory__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in synapse/v1/memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryServiceStub:
    """=== Memory Service ===

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/synapse.v1.MemoryService/Add',
                request_serializer=synapse_dot_v1_dot_memory__pb2.AddRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_memory__pb2.AddResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/synapse.v1.MemoryService/Update',
                request_serializer=synapse_dot_v1_dot_memory__pb2.UpdateRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_memory__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.Forget = channel.unary_unary(
                '/synapse.v1.MemoryService/Forget',
                request_serializer=synapse_dot_v1_dot_memory__pb2.ForgetRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_memory__pb2.ForgetResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/synapse.v1.MemoryService/Get',
                request_serializer=synapse_dot_v1_dot_memory__pb2.GetRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_memory__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/synapse.v1.MemoryService/Search',
                request_serializer=synapse_dot_v1_dot_memory__pb2.SearchRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_memory__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/synapse.v1.MemoryService/List',
                request_serializer=synapse_dot_v1_dot_memory__pb2.ListRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_memory__pb2.ListResponse.FromString,
                _registered_method=True)
        self.History = channel.unary_unary(
                '/synapse.v1.MemoryService/History',
                request_serializer=synapse_dot_v1_dot_memory__pb2.HistoryRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_memory__pb2.HistoryResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/synapse.v1.MemoryService/Subscribe',
                request_serializer=synapse_dot_v1_dot_memory__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_memory__pb2.MemoryEvent.FromString,
                _registered_method=True)
        self.BatchAdd = channel.unary_unary(
                '/synapse.v1.MemoryService/BatchAdd',
                request_serializer=synapse_dot_v1_dot_memory__pb2.BatchAddRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_memory__pb2.BatchAddResponse.FromString,
                _registered_method=True)
        self.Export = channel.unary_stream(
                '/synapse.v1.MemoryService/Export',
                request_serializer=synapse_dot_v1_dot_memory__pb2.ExportRequest.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_memory__pb2.MemoryRecord.FromString,
                _registered_method=True)
        self.Import = channel.stream_unary(
                '/synapse.v1.MemoryService/Import',
                request_serializer=synapse_dot_v1_dot_memory__pb2.MemoryRecord.SerializeToString,
                response_deserializer=synapse_dot_v1_dot_memory__pb2.ImportResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer:
    """=== Memory Service ===

    """

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def History(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Export(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Import(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=synapse_dot_v1_dot_memory__pb2.AddRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_memory__pb2.AddResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=synapse_dot_v1_dot_memory__pb2.UpdateRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_memory__pb2.UpdateResponse.SerializeToString,
            ),
            'Forget': grpc.unary_unary_rpc_method_handler(
                    servicer.Forget,
                    request_deserializer=synapse_dot_v1_dot_memory__pb2.ForgetRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_memory__pb2.ForgetResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=synapse_dot_v1_dot_memory__pb2.GetRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_memory__pb2.GetResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=synapse_dot_v1_dot_memory__pb2.SearchRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_memory__pb2.SearchResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=synapse_dot_v1_dot_memory__pb2.ListRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_memory__pb2.ListResponse.SerializeToString,
            ),
            'History': grpc.unary_unary_rpc_method_handler(
                    servicer.History,
                    request_deserializer=synapse_dot_v1_dot_memory__pb2.HistoryRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_memory__pb2.HistoryResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=synapse_dot_v1_dot_memory__pb2.SubscribeRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_memory__pb2.MemoryEvent.SerializeToString,
            ),
            'BatchAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchAdd,
                    request_deserializer=synapse_dot_v1_dot_memory__pb2.BatchAddRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_memory__pb2.BatchAddResponse.SerializeToString,
            ),
            'Export': grpc.unary_stream_rpc_method_handler(
                    servicer.Export,
                    request_deserializer=synapse_dot_v1_dot_memory__pb2.ExportRequest.FromString,
                    response_serializer=synapse_dot_v1_dot_memory__pb2.MemoryRecord.SerializeToString,
            ),
            'Import': grpc.stream_unary_rpc_method_handler(
                    servicer.Import,
                    request_deserializer=synapse_dot_v1_dot_memory__pb2.MemoryRecord.FromString,
                    response_serializer=synapse_dot_v1_dot_memory__pb2.ImportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synapse.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('synapse.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService:
    """=== Memory Service ===

    """

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.MemoryService/Add',
            synapse_dot_v1_dot_memory__pb2.AddRequest.SerializeToString,
            synapse_dot_v1_dot_memory__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.MemoryService/Update',
            synapse_dot_v1_dot_memory__pb2.UpdateRequest.SerializeToString,
            synapse_dot_v1_dot_memory__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.MemoryService/Forget',
            synapse_dot_v1_dot_memory__pb2.ForgetRequest.SerializeToString,
            synapse_dot_v1_dot_memory__pb2.ForgetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.MemoryService/Get',
            synapse_dot_v1_dot_memory__pb2.GetRequest.SerializeToString,
            synapse_dot_v1_dot_memory__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.MemoryService/Search',
            synapse_dot_v1_dot_memory__pb2.SearchRequest.SerializeToString,
            synapse_dot_v1_dot_memory__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.MemoryService/List',
            synapse_dot_v1_dot_memory__pb2.ListRequest.SerializeToString,
            synapse_dot_v1_dot_memory__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def History(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.MemoryService/History',
            synapse_dot_v1_dot_memory__pb2.HistoryRequest.SerializeToString,
            synapse_dot_v1_dot_memory__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/synapse.v1.MemoryService/Subscribe',
            synapse_dot_v1_dot_memory__pb2.SubscribeRequest.SerializeToString,
            synapse_dot_v1_dot_memory__pb2.MemoryEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.v1.MemoryService/BatchAdd',
            synapse_dot_v1_dot_memory__pb2.BatchAddRequest.SerializeToString,
            synapse_dot_v1_dot_memory__pb2.BatchAddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Export(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/synapse.v1.MemoryService/Export',
            synapse_dot_v1_dot_memory__pb2.ExportRequest.SerializeToString,
            synapse_dot_v1_dot_memory__pb2.MemoryRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Import(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/synapse.v1.MemoryService/Import',
            synapse_dot_v1_dot_memory__pb2.MemoryRecord.SerializeToString,
            synapse_dot_v1_dot_memory__pb2.ImportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
